# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 416)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 691, 371))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(20, 60, 54, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(560, 60, 71, 17))
        self.label_2.setObjectName("label_2")
        self.grupos = QtWidgets.QComboBox(self.page)
        self.grupos.setGeometry(QtCore.QRect(20, 80, 81, 31))
        self.grupos.setObjectName("grupos")
        self.chatlist = QtWidgets.QListWidget(self.page)
        self.chatlist.setGeometry(QtCore.QRect(110, 80, 421, 161))
        self.chatlist.setObjectName("chatlist")
        self.listconectados = QtWidgets.QListWidget(self.page)
        self.listconectados.setGeometry(QtCore.QRect(550, 80, 111, 121))
        self.listconectados.setObjectName("listconectados")
        self.linesend = QtWidgets.QLineEdit(self.page)
        self.linesend.setGeometry(QtCore.QRect(110, 270, 421, 25))
        self.linesend.setObjectName("linesend")
        self.sendbtn = QtWidgets.QPushButton(self.page)
        self.sendbtn.setGeometry(QtCore.QRect(540, 270, 80, 25))
        self.sendbtn.setObjectName("sendbtn")
        self.bt_logout = QtWidgets.QPushButton(self.page)
        self.bt_logout.setGeometry(QtCore.QRect(280, 320, 80, 25))
        self.bt_logout.setObjectName("bt_logout")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.RSenha = QtWidgets.QLineEdit(self.page_3)
        self.RSenha.setGeometry(QtCore.QRect(350, 120, 113, 25))
        self.RSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.RSenha.setObjectName("RSenha")
        self.Registrar = QtWidgets.QPushButton(self.page_3)
        self.Registrar.setGeometry(QtCore.QRect(320, 210, 80, 25))
        self.Registrar.setObjectName("Registrar")
        self.confSenha = QtWidgets.QLineEdit(self.page_3)
        self.confSenha.setGeometry(QtCore.QRect(350, 160, 113, 25))
        self.confSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confSenha.setObjectName("confSenha")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(290, 70, 54, 17))
        self.label_5.setObjectName("label_5")
        self.RUsuario = QtWidgets.QLineEdit(self.page_3)
        self.RUsuario.setGeometry(QtCore.QRect(350, 70, 113, 25))
        self.RUsuario.setObjectName("RUsuario")
        self.labelsenha = QtWidgets.QLabel(self.page_3)
        self.labelsenha.setGeometry(QtCore.QRect(290, 120, 54, 17))
        self.labelsenha.setObjectName("labelsenha")
        self.label_warning_create = QtWidgets.QLabel(self.page_3)
        self.label_warning_create.setGeometry(QtCore.QRect(243, 270, 271, 20))
        self.label_warning_create.setText("")
        self.label_warning_create.setObjectName("label_warning_create")
        self.labelconfsenha = QtWidgets.QLabel(self.page_3)
        self.labelconfsenha.setGeometry(QtCore.QRect(243, 160, 101, 20))
        self.labelconfsenha.setObjectName("labelconfsenha")
        self.bt_voltar = QtWidgets.QPushButton(self.page_3)
        self.bt_voltar.setGeometry(QtCore.QRect(410, 210, 71, 25))
        self.bt_voltar.setObjectName("bt_voltar")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Senha = QtWidgets.QLineEdit(self.page_2)
        self.Senha.setGeometry(QtCore.QRect(300, 120, 113, 25))
        self.Senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Senha.setObjectName("Senha")
        self.Login = QtWidgets.QPushButton(self.page_2)
        self.Login.setGeometry(QtCore.QRect(300, 170, 80, 25))
        self.Login.setObjectName("Login")
        self.Registrarse = QtWidgets.QPushButton(self.page_2)
        self.Registrarse.setGeometry(QtCore.QRect(300, 230, 80, 25))
        self.Registrarse.setObjectName("Registrarse")
        self.Usuario = QtWidgets.QLineEdit(self.page_2)
        self.Usuario.setGeometry(QtCore.QRect(300, 70, 113, 25))
        self.Usuario.setObjectName("Usuario")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(250, 200, 191, 20))
        self.label_3.setObjectName("label_3")
        self.lSenha = QtWidgets.QLabel(self.page_2)
        self.lSenha.setGeometry(QtCore.QRect(240, 120, 54, 17))
        self.lSenha.setObjectName("lSenha")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(240, 70, 54, 17))
        self.label_4.setObjectName("label_4")
        self.label_warning = QtWidgets.QLabel(self.page_2)
        self.label_warning.setGeometry(QtCore.QRect(200, 270, 271, 20))
        self.label_warning.setText("")
        self.label_warning.setObjectName("label_warning")
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 706, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Grupos"))
        self.label_2.setText(_translate("MainWindow", "Conectados"))
        self.sendbtn.setText(_translate("MainWindow", "Enviar"))
        self.bt_logout.setText(_translate("MainWindow", "LogOut"))
        self.Registrar.setText(_translate("MainWindow", "Registrar"))
        self.label_5.setText(_translate("MainWindow", "Usuario:"))
        self.labelsenha.setText(_translate("MainWindow", "Senha:"))
        self.labelconfsenha.setText(_translate("MainWindow", "Confirmar senha:"))
        self.bt_voltar.setText(_translate("MainWindow", "Voltar"))
        self.Login.setText(_translate("MainWindow", "Login"))
        self.Registrarse.setText(_translate("MainWindow", "Registrar-se "))
        self.label_3.setText(_translate("MainWindow", "Não possui conta ?  Registre-se"))
        self.lSenha.setText(_translate("MainWindow", "Senha:"))
        self.label_4.setText(_translate("MainWindow", "Usuario:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

