# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 416)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 0, 691, 371))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(160, 20, 54, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(560, 60, 71, 17))
        self.label_2.setObjectName("label_2")
        self.grupos = QtWidgets.QComboBox(self.page)
        self.grupos.setGeometry(QtCore.QRect(200, 20, 81, 31))
        self.grupos.setObjectName("grupos")
        self.chatlist = QtWidgets.QListWidget(self.page)
        self.chatlist.setGeometry(QtCore.QRect(150, 70, 391, 161))
        self.chatlist.setObjectName("chatlist")
        self.listconectados = QtWidgets.QListWidget(self.page)
        self.listconectados.setGeometry(QtCore.QRect(550, 80, 111, 121))
        self.listconectados.setObjectName("listconectados")
        self.linesend = QtWidgets.QLineEdit(self.page)
        self.linesend.setGeometry(QtCore.QRect(170, 270, 421, 25))
        self.linesend.setObjectName("linesend")
        self.sendbtn = QtWidgets.QPushButton(self.page)
        self.sendbtn.setGeometry(QtCore.QRect(530, 330, 80, 25))
        self.sendbtn.setObjectName("sendbtn")
        self.bt_logout = QtWidgets.QPushButton(self.page)
        self.bt_logout.setGeometry(QtCore.QRect(30, 330, 80, 25))
        self.bt_logout.setObjectName("bt_logout")
        self.label_15 = QtWidgets.QLabel(self.page)
        self.label_15.setGeometry(QtCore.QRect(0, 130, 144, 61))
        self.label_15.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_15.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label_15.setObjectName("label_15")
        self.label_11 = QtWidgets.QLabel(self.page)
        self.label_11.setGeometry(QtCore.QRect(0, 10, 144, 361))
        self.label_11.setMaximumSize(QtCore.QSize(144, 400))
        self.label_11.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_16 = QtWidgets.QLabel(self.page)
        self.label_16.setGeometry(QtCore.QRect(140, 10, 531, 361))
        self.label_16.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 214), stop:1 rgba(179, 179, 179, 216));")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page)
        self.label_17.setGeometry(QtCore.QRect(0, 10, 144, 61))
        self.label_17.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_17.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.page)
        self.label_18.setGeometry(QtCore.QRect(0, 190, 144, 61))
        self.label_18.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_18.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_20 = QtWidgets.QLabel(self.page)
        self.label_20.setGeometry(QtCore.QRect(0, 310, 144, 61))
        self.label_20.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_20.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.page)
        self.label_21.setGeometry(QtCore.QRect(0, 250, 144, 61))
        self.label_21.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_21.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.label_19 = QtWidgets.QLabel(self.page)
        self.label_19.setGeometry(QtCore.QRect(0, 70, 144, 61))
        self.label_19.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_19.setStyleSheet("background-color: rgba(32, 234, 49, 100);\n"
"color: rgb(230, 230, 230);")
        self.label_19.setObjectName("label_19")
        self.enviararquivo = QtWidgets.QPushButton(self.page)
        self.enviararquivo.setGeometry(QtCore.QRect(10, 270, 111, 25))
        self.enviararquivo.setObjectName("enviararquivo")
        self.label_11.raise_()
        self.label_16.raise_()
        self.label_20.raise_()
        self.label_15.raise_()
        self.label_18.raise_()
        self.label_17.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.grupos.raise_()
        self.chatlist.raise_()
        self.listconectados.raise_()
        self.linesend.raise_()
        self.sendbtn.raise_()
        self.bt_logout.raise_()
        self.label_21.raise_()
        self.label_19.raise_()
        self.enviararquivo.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.RSenha = QtWidgets.QLineEdit(self.page_3)
        self.RSenha.setGeometry(QtCore.QRect(350, 120, 113, 25))
        self.RSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.RSenha.setObjectName("RSenha")
        self.Registrar = QtWidgets.QPushButton(self.page_3)
        self.Registrar.setGeometry(QtCore.QRect(320, 210, 80, 25))
        self.Registrar.setObjectName("Registrar")
        self.confSenha = QtWidgets.QLineEdit(self.page_3)
        self.confSenha.setGeometry(QtCore.QRect(350, 160, 113, 25))
        self.confSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confSenha.setObjectName("confSenha")
        self.label_5 = QtWidgets.QLabel(self.page_3)
        self.label_5.setGeometry(QtCore.QRect(290, 70, 54, 17))
        self.label_5.setObjectName("label_5")
        self.RUsuario = QtWidgets.QLineEdit(self.page_3)
        self.RUsuario.setGeometry(QtCore.QRect(350, 70, 113, 25))
        self.RUsuario.setObjectName("RUsuario")
        self.labelsenha = QtWidgets.QLabel(self.page_3)
        self.labelsenha.setGeometry(QtCore.QRect(290, 120, 54, 17))
        self.labelsenha.setObjectName("labelsenha")
        self.label_warning_create = QtWidgets.QLabel(self.page_3)
        self.label_warning_create.setGeometry(QtCore.QRect(243, 270, 271, 20))
        self.label_warning_create.setText("")
        self.label_warning_create.setObjectName("label_warning_create")
        self.labelconfsenha = QtWidgets.QLabel(self.page_3)
        self.labelconfsenha.setGeometry(QtCore.QRect(243, 160, 101, 20))
        self.labelconfsenha.setObjectName("labelconfsenha")
        self.bt_voltar = QtWidgets.QPushButton(self.page_3)
        self.bt_voltar.setGeometry(QtCore.QRect(410, 210, 71, 25))
        self.bt_voltar.setObjectName("bt_voltar")
        self.label_45 = QtWidgets.QLabel(self.page_3)
        self.label_45.setGeometry(QtCore.QRect(0, 0, 144, 61))
        self.label_45.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_45.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.page_3)
        self.label_46.setGeometry(QtCore.QRect(0, 120, 144, 61))
        self.label_46.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_46.setStyleSheet("background-color: rgba(32, 234, 49, 100);\n"
"color: rgb(230, 230, 230);")
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.page_3)
        self.label_47.setGeometry(QtCore.QRect(0, 240, 144, 61))
        self.label_47.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_47.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label_47.setText("")
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.page_3)
        self.label_48.setGeometry(QtCore.QRect(0, 180, 144, 61))
        self.label_48.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_48.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.page_3)
        self.label_49.setGeometry(QtCore.QRect(140, 0, 531, 361))
        self.label_49.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 214), stop:1 rgba(179, 179, 179, 216));")
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.label_51 = QtWidgets.QLabel(self.page_3)
        self.label_51.setGeometry(QtCore.QRect(0, 300, 144, 61))
        self.label_51.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_51.setFont(font)
        self.label_51.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_51.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.label_50 = QtWidgets.QLabel(self.page_3)
        self.label_50.setGeometry(QtCore.QRect(0, 60, 144, 61))
        self.label_50.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_50.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.label_50.setObjectName("label_50")
        self.label_49.raise_()
        self.label_45.raise_()
        self.label_51.raise_()
        self.label_48.raise_()
        self.label_47.raise_()
        self.label_46.raise_()
        self.RSenha.raise_()
        self.Registrar.raise_()
        self.confSenha.raise_()
        self.label_5.raise_()
        self.RUsuario.raise_()
        self.labelsenha.raise_()
        self.label_warning_create.raise_()
        self.labelconfsenha.raise_()
        self.bt_voltar.raise_()
        self.label_50.raise_()
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.Senha = QtWidgets.QLineEdit(self.page_2)
        self.Senha.setGeometry(QtCore.QRect(320, 160, 200, 25))
        self.Senha.setMaximumSize(QtCore.QSize(200, 25))
        self.Senha.setStyleSheet("background-color: rgb(204, 204, 153);")
        self.Senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Senha.setObjectName("Senha")
        self.Login = QtWidgets.QPushButton(self.page_2)
        self.Login.setGeometry(QtCore.QRect(440, 200, 80, 25))
        self.Login.setMaximumSize(QtCore.QSize(80, 25))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(28, 198, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 198, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 198, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 198, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 198, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 198, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 198, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 198, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(28, 198, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Login.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans Unicode")
        font.setPointSize(10)
        font.setItalic(True)
        self.Login.setFont(font)
        self.Login.setStyleSheet("background-color: rgb(28, 198, 25);")
        self.Login.setObjectName("Login")
        self.Registrarse = QtWidgets.QPushButton(self.page_2)
        self.Registrarse.setGeometry(QtCore.QRect(380, 280, 91, 31))
        self.Registrarse.setMaximumSize(QtCore.QSize(145, 100))
        self.Registrarse.setObjectName("Registrarse")
        self.Usuario = QtWidgets.QLineEdit(self.page_2)
        self.Usuario.setGeometry(QtCore.QRect(320, 120, 200, 25))
        self.Usuario.setMaximumSize(QtCore.QSize(200, 25))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Usuario.setFont(font)
        self.Usuario.setStyleSheet("background-color: rgb(204, 204, 153);")
        self.Usuario.setObjectName("Usuario")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(340, 260, 191, 20))
        self.label_3.setMaximumSize(QtCore.QSize(191, 20))
        self.label_3.setObjectName("label_3")
        self.label_warning = QtWidgets.QLabel(self.page_2)
        self.label_warning.setGeometry(QtCore.QRect(230, 60, 271, 20))
        self.label_warning.setMaximumSize(QtCore.QSize(271, 20))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_warning.setFont(font)
        self.label_warning.setStyleSheet("color: rgb(255, 1, 1);")
        self.label_warning.setText("")
        self.label_warning.setObjectName("label_warning")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(260, 50, 331, 271))
        self.label_6.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0.153409, x2:1, y2:0, stop:0 rgba(0, 0, 0, 214), stop:1 rgba(179, 179, 179, 216));")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(260, 80, 331, 251))
        self.label_7.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(270, 55, 261, 21))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(self.page_2)
        self.checkBox.setGeometry(QtCore.QRect(320, 200, 81, 31))
        self.checkBox.setObjectName("checkBox")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        self.label_8.setGeometry(QtCore.QRect(0, 10, 144, 361))
        self.label_8.setMaximumSize(QtCore.QSize(144, 400))
        self.label_8.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(140, 10, 531, 361))
        self.label_9.setStyleSheet("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(0, 0, 0, 214), stop:1 rgba(179, 179, 179, 216));")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(0, 10, 144, 61))
        self.label_10.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_10.setStyleSheet("background-color: rgba(32, 234, 49, 100);\n"
"color: rgb(230, 230, 230);")
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.page_2)
        self.label_12.setGeometry(QtCore.QRect(0, 130, 144, 61))
        self.label_12.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_12.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_2)
        self.label_13.setGeometry(QtCore.QRect(0, 70, 144, 61))
        self.label_13.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_13.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.label_13.setObjectName("label_13")
        self.label_42 = QtWidgets.QLabel(self.page_2)
        self.label_42.setGeometry(QtCore.QRect(0, 250, 144, 61))
        self.label_42.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_42.setStyleSheet("background-color: rgb(218, 218, 218);")
        self.label_42.setText("")
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.page_2)
        self.label_43.setGeometry(QtCore.QRect(0, 190, 144, 61))
        self.label_43.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_43.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.label_43.setText("")
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.page_2)
        self.label_44.setGeometry(QtCore.QRect(0, 310, 144, 61))
        self.label_44.setMaximumSize(QtCore.QSize(144, 400))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_44.setStyleSheet("background-color: rgb(203, 203, 203);")
        self.label_44.setText("")
        self.label_44.setObjectName("label_44")
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.Senha.raise_()
        self.Login.raise_()
        self.Registrarse.raise_()
        self.Usuario.raise_()
        self.label_3.raise_()
        self.label_warning.raise_()
        self.label_4.raise_()
        self.checkBox.raise_()
        self.label_10.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_42.raise_()
        self.label_43.raise_()
        self.label_44.raise_()
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 706, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Grupos"))
        self.label_2.setText(_translate("MainWindow", "Conectados"))
        self.sendbtn.setText(_translate("MainWindow", "Enviar"))
        self.bt_logout.setText(_translate("MainWindow", "LogOut"))
        self.label_15.setText(_translate("MainWindow", "      Register"))
        self.label_17.setText(_translate("MainWindow", "        Login"))
        self.label_19.setText(_translate("MainWindow", "       Login"))
        self.enviararquivo.setText(_translate("MainWindow", "Enviar Arquivo"))
        self.Registrar.setText(_translate("MainWindow", "Registrar"))
        self.label_5.setText(_translate("MainWindow", "Usuario:"))
        self.labelsenha.setText(_translate("MainWindow", "Senha:"))
        self.labelconfsenha.setText(_translate("MainWindow", "Confirmar senha:"))
        self.bt_voltar.setText(_translate("MainWindow", "Voltar"))
        self.label_45.setText(_translate("MainWindow", "        Login"))
        self.label_46.setText(_translate("MainWindow", "    Register"))
        self.label_50.setText(_translate("MainWindow", "        Chat"))
        self.Senha.setText(_translate("MainWindow", "user"))
        self.Login.setText(_translate("MainWindow", "Login"))
        self.Registrarse.setText(_translate("MainWindow", "Registrar-se "))
        self.Usuario.setAccessibleDescription(_translate("MainWindow", "User"))
        self.Usuario.setText(_translate("MainWindow", "user"))
        self.Usuario.setPlaceholderText(_translate("MainWindow", "user"))
        self.label_3.setText(_translate("MainWindow", "Não possui conta ?  Registre-se"))
        self.label_4.setText(_translate("MainWindow", "Please login"))
        self.checkBox.setText(_translate("MainWindow", "Remember"))
        self.label_10.setText(_translate("MainWindow", "       Login"))
        self.label_12.setText(_translate("MainWindow", "      Register"))
        self.label_13.setText(_translate("MainWindow", "        Chat"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

